import { Component, OnInit, AfterViewInit, ElementRef } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { SeoService } from '../../core/services/seo.service';
import { ScrollRevealService } from '../../core/services/scroll-reveal.service';
import { DESTINATIONS, Destination } from '../../core/data/destinations.data';

interface CourseData {
  id: string; slug: string; name: string; fullName: string; tagline: string;
  icon: string; color: string; shortDescription: string;
  heroTitle: string; heroSubtitle: string; overview: string;
  whoShouldJoin: string[]; whatYouWillLearn: string[]; methodology: string[];
  duration: string; mode: string; batchSize: string; highlights: string[];
  faqs: { question: string; answer: string }[];
  seoTitle: string; seoDescription: string;
}

@Component({
  selector: 'app-course-detail',
  templateUrl: './course-detail.component.html',
  styleUrls: ['./course-detail.component.scss'],
})
export class CourseDetailComponent implements OnInit, AfterViewInit {
  course!: CourseData;
  slug = '';
  relatedDestinations: Destination[] = [];

  private courseCountryMap: Record<string, string[]> = {
    'ielts-coaching': ['canada', 'united-kingdom', 'australia', 'new-zealand', 'ireland'],
    'toefl-coaching': ['united-states', 'canada', 'germany', 'france', 'singapore'],
    'gre-coaching': ['united-states', 'united-kingdom', 'singapore', 'germany', 'australia'],
    'gmat-coaching': ['united-states', 'united-kingdom', 'singapore', 'dubai-uae', 'france'],
    'spoken-english': ['canada', 'united-kingdom', 'australia', 'ireland', 'new-zealand'],
    'german-classes': ['germany'],
    'french-classes': ['france', 'canada'],
    'japanese-classes': ['japan'],
    'pte-oet-duolingo': ['australia', 'new-zealand', 'united-kingdom', 'canada', 'ireland'],
  };

  private coursesData: CourseData[] = [
    { id: 'ielts', slug: 'ielts-coaching', name: 'IELTS', fullName: 'IELTS Coaching', tagline: 'International English Language Testing System', icon: 'bi-translate', color: '#C62828', shortDescription: 'Achieve your target band score with expert coaching and regular mock tests.', heroTitle: 'IELTS Coaching in Trichy', heroSubtitle: 'Master all four modules — Listening, Reading, Writing & Speaking — with structured coaching and regular mock tests.', overview: 'The International English Language Testing System (IELTS) is the world\'s most popular English proficiency test for study, work, and migration. At Success Learning, our IELTS programme is designed to help you achieve your target band score through expert instruction, intensive practice, and personalised feedback. Whether you\'re aiming for Academic or General Training, our trainers break down each module systematically so you build real confidence.', whoShouldJoin: ['Students planning to study abroad in UK, Australia, Canada, or New Zealand', 'Working professionals seeking international career opportunities', 'Individuals applying for permanent residency or migration', 'Anyone needing to demonstrate English proficiency for visa applications'], whatYouWillLearn: ['Listening strategies for various question types and accents', 'Reading techniques including skimming, scanning, and inference', 'Writing Task 1 & Task 2 with band-9 structures', 'Speaking confidence for all three parts of the interview', 'Time management and exam-day strategies', 'Vocabulary building for academic and general contexts'], methodology: ['Diagnostic test to assess your current level', 'Module-wise structured training with daily targets', 'Weekly full-length mock tests under exam conditions', 'One-on-one speaking practice sessions', 'Detailed written feedback on writing tasks', 'Error analysis and personalised improvement plan'], duration: '4–8 Weeks', mode: 'Online & Offline', batchSize: '5–8 Students', highlights: ['Mock Tests', 'Speaking Practice', 'Writing Review', 'Study Materials'], faqs: [{ question: 'What IELTS band score can I expect?', answer: 'Most students improve by 1–2 bands. Your final score depends on starting level, consistency, and practice.' }, { question: 'Do you offer both Academic and General Training?', answer: 'Yes, we offer coaching for both IELTS Academic and General Training modules.' }, { question: 'How often are mock tests conducted?', answer: 'Full-length mock tests weekly. Module-specific practice tests after each topic.' }, { question: 'Can I join if my English is beginner level?', answer: 'Yes, we have a foundation batch that builds core English skills first.' }], seoTitle: 'IELTS Coaching in Trichy | Success Learning', seoDescription: 'Expert IELTS coaching in Trichy. Small batches, mock tests, personalised feedback. Thillai Nagar. Call 98409 79292.' },
    { id: 'toefl', slug: 'toefl-coaching', name: 'TOEFL', fullName: 'TOEFL Coaching', tagline: 'Test of English as a Foreign Language', icon: 'bi-globe2', color: '#1565C0', shortDescription: 'Comprehensive TOEFL iBT preparation.', heroTitle: 'TOEFL Coaching in Trichy', heroSubtitle: 'Score high on TOEFL iBT with structured training and computer-based mock tests.', overview: 'TOEFL (Test of English as a Foreign Language) is widely accepted by universities across the USA, Canada, and Europe. Our TOEFL iBT coaching covers all four sections with focus on integrated tasks. Our computer-based practice environment ensures you\'re fully prepared for test day.', whoShouldJoin: ['Students applying to US and Canadian universities', 'Professionals seeking English proficiency certification', 'Anyone preparing for English-medium higher education abroad'], whatYouWillLearn: ['Reading comprehension for academic passages', 'Listening skills for lectures and conversations', 'Integrated and independent speaking tasks', 'Integrated and independent writing', 'Note-taking strategies', 'Time management for each section'], methodology: ['Initial proficiency assessment', 'Section-wise training with progressive difficulty', 'Computer-based practice simulating real TOEFL', 'Regular timed mock tests with scoring', 'Detailed review of speaking recordings', 'Targeted practice for weak areas'], duration: '4–6 Weeks', mode: 'Online & Offline', batchSize: '5–8 Students', highlights: ['Computer-Based Practice', 'Integrated Tasks', 'Speaking Recordings', 'Score Improvement'], faqs: [{ question: 'What is the difference between TOEFL and IELTS?', answer: 'TOEFL is computer-based with American English; IELTS has a face-to-face speaking test with British English.' }, { question: 'Do you provide computer-based practice?', answer: 'Yes, we simulate the actual TOEFL iBT test environment for all practice sessions.' }], seoTitle: 'TOEFL Coaching in Trichy | Success Learning', seoDescription: 'TOEFL iBT coaching in Trichy. Computer-based practice, mock tests, small batches. Call 98409 79292.' },
    { id: 'gre', slug: 'gre-coaching', name: 'GRE', fullName: 'GRE Coaching', tagline: 'Graduate Record Examination', icon: 'bi-calculator', color: '#2E7D32', shortDescription: 'Master Verbal, Quantitative & AWA.', heroTitle: 'GRE Coaching in Trichy', heroSubtitle: 'Build strong foundations in Verbal Reasoning, Quantitative Analysis & Analytical Writing.', overview: 'The GRE is required by most graduate schools worldwide. Our programme focuses on building fundamental skills, teaching test-taking strategies, and providing extensive practice. We simplify complex quantitative concepts and build your vocabulary systematically.', whoShouldJoin: ['Students applying for MS or PhD programmes abroad', 'Professionals seeking MBA admissions at GRE-accepting schools'], whatYouWillLearn: ['Verbal Reasoning — vocabulary, text completion, reading comprehension', 'Quantitative Reasoning — arithmetic, algebra, geometry, data analysis', 'Analytical Writing — Issue and Argument essays', 'Adaptive test strategies', 'High-frequency GRE vocabulary'], methodology: ['Diagnostic test and personalised study plan', 'Concept-based teaching', 'Weekly sectional and full-length mock tests', 'Vocabulary building with contextual learning', 'Essay review with scoring feedback'], duration: '6–10 Weeks', mode: 'Online & Offline', batchSize: '4–6 Students', highlights: ['Adaptive Practice', 'Vocabulary Building', 'Essay Review', 'Strategy Sessions'], faqs: [{ question: 'How long does GRE preparation take?', answer: '2–3 months of consistent preparation for most students.' }, { question: 'What score can I target?', answer: 'After a diagnostic test, we set realistic targets. Most students score 310+.' }], seoTitle: 'GRE Coaching in Trichy | Success Learning', seoDescription: 'GRE coaching in Trichy. Expert trainers, mock tests, small batches. Thillai Nagar. Call 98409 79292.' },
    { id: 'gmat', slug: 'gmat-coaching', name: 'GMAT', fullName: 'GMAT Coaching', tagline: 'Graduate Management Admission Test', icon: 'bi-graph-up-arrow', color: '#E65100', shortDescription: 'Strategic GMAT preparation for MBA aspirants.', heroTitle: 'GMAT Coaching in Trichy', heroSubtitle: 'Crack the GMAT with expert coaching in Quantitative, Verbal, Data Insights & Analytical Writing.', overview: 'The GMAT is the gold standard for MBA admissions worldwide. We focus on building analytical and critical thinking skills the GMAT demands with adaptive difficulty practice.', whoShouldJoin: ['MBA aspirants targeting top business schools', 'Professionals planning career transitions'], whatYouWillLearn: ['Quantitative Reasoning', 'Verbal Reasoning', 'Data Insights', 'Analytical Writing Assessment', 'Adaptive test strategies'], methodology: ['Baseline assessment and customised study plan', 'Concept-first teaching', 'Regular adaptive mock tests', 'Score analysis and improvement tracking', 'One-on-one doubt clearing'], duration: '8–12 Weeks', mode: 'Online & Offline', batchSize: '4–6 Students', highlights: ['Adaptive Practice', 'Score Analytics', 'MBA Guidance', 'Small Batches'], faqs: [{ question: 'Is the GMAT Focus Edition covered?', answer: 'Yes, our curriculum is updated for the GMAT Focus Edition format.' }, { question: 'Can I prepare alongside my job?', answer: 'Yes, we offer flexible timings including weekends and evenings.' }], seoTitle: 'GMAT Coaching in Trichy | Success Learning', seoDescription: 'GMAT coaching in Trichy. Adaptive mock tests, small batches. Thillai Nagar. Call 98409 79292.' },
    { id: 'spoken-english', slug: 'spoken-english', name: 'Spoken English', fullName: 'Spoken English Training', tagline: 'Communicate with Confidence', icon: 'bi-chat-quote', color: '#6A1B9A', shortDescription: 'Build fluency and confidence.', heroTitle: 'Spoken English Training in Trichy', heroSubtitle: 'From hesitation to fluency — learn to speak English confidently.', overview: 'Our Spoken English programme focuses on practical speaking skills — everyday conversations, group discussions, presentations, and interview preparation. Our interactive approach ensures you start speaking from day one.', whoShouldJoin: ['Students wanting to improve communication', 'Working professionals preparing for interviews', 'Anyone wanting to communicate effectively in English'], whatYouWillLearn: ['Pronunciation and intonation improvement', 'Vocabulary for daily and professional settings', 'Grammar essentials in speaking context', 'Group discussion and debate skills', 'Presentation and public speaking basics', 'Interview communication techniques'], methodology: ['Interactive sessions — all practice', 'Role-playing real-world scenarios', 'Daily speaking assignments', 'Pronunciation drills', 'Confidence-building activities', 'Regular progress assessments'], duration: '4–12 Weeks', mode: 'Online & Offline', batchSize: '6–10 Students', highlights: ['Interactive Sessions', 'Daily Practice', 'Pronunciation Focus', 'Interview Prep'], faqs: [{ question: 'I know grammar but can\'t speak fluently. Will this help?', answer: 'Yes, we focus on converting passive knowledge into active speaking skills.' }, { question: 'How soon will I see improvement?', answer: 'Most students notice significant improvement within 3–4 weeks.' }], seoTitle: 'Spoken English Classes in Trichy | Success Learning', seoDescription: 'Spoken English training in Trichy. Interactive sessions, small batches. Thillai Nagar. Call 98409 79292.' },
    { id: 'german', slug: 'german-classes', name: 'German', fullName: 'German Language Classes', tagline: 'A1 to B2 Levels', icon: 'bi-flag', color: '#37474F', shortDescription: 'Learn German from A1 to B2.', heroTitle: 'German Language Classes in Trichy', heroSubtitle: 'Master German from basics to advanced — Goethe-Zertifikat preparation.', overview: 'Germany is a top destination for higher education and career opportunities. Our programme takes you from A1 through B2 level following the CEFR framework and prepares you for Goethe-Zertifikat examinations.', whoShouldJoin: ['Students planning to study in Germany', 'Professionals targeting German-speaking countries', 'Anyone preparing for Goethe-Zertifikat exams'], whatYouWillLearn: ['German grammar — basics to complex structures', 'Vocabulary for everyday and academic contexts', 'Listening and comprehension', 'Speaking and conversational German', 'Reading and writing per CEFR levels'], methodology: ['Level-wise structured curriculum', 'Audio-visual learning materials', 'Conversational practice every session', 'Regular Goethe-pattern assessments', 'Cultural context integration'], duration: '3–4 Months per level', mode: 'Online & Offline', batchSize: '5–8 Students', highlights: ['CEFR Levels', 'Goethe Prep', 'Conversational Focus', 'Cultural Context'], faqs: [{ question: 'Which levels do you offer?', answer: 'A1, A2, B1, and B2 following the CEFR framework.' }, { question: 'Do you prepare for Goethe-Zertifikat?', answer: 'Yes, our curriculum aligns with Goethe exam patterns with mock tests.' }], seoTitle: 'German Language Classes in Trichy | Success Learning', seoDescription: 'German classes in Trichy. A1 to B2, Goethe preparation. Thillai Nagar. Call 98409 79292.' },
    { id: 'french', slug: 'french-classes', name: 'French', fullName: 'French Language Classes', tagline: 'A1 to B2 Levels', icon: 'bi-flag', color: '#0D47A1', shortDescription: 'Learn French from A1 to B2.', heroTitle: 'French Language Classes in Trichy', heroSubtitle: 'Structured French language training for study, career, and DELF preparation.', overview: 'French is spoken across five continents. Our programme covers A1–B2 levels with grammar, vocabulary, and conversational skills, plus DELF and TCF exam preparation.', whoShouldJoin: ['Students planning to study in French-speaking countries', 'Professionals seeking opportunities in French-speaking regions', 'Anyone preparing for DELF or TCF exams'], whatYouWillLearn: ['French grammar and sentence construction', 'Everyday and academic vocabulary', 'Listening comprehension', 'Conversational French', 'Reading and writing skills'], methodology: ['CEFR-aligned curriculum', 'Interactive sessions with speaking focus', 'Audio-visual resources', 'Regular DELF-pattern mock tests', 'Cultural immersion activities'], duration: '3–4 Months per level', mode: 'Online & Offline', batchSize: '5–8 Students', highlights: ['CEFR Levels', 'DELF Prep', 'Cultural Immersion', 'Speaking Focus'], faqs: [{ question: 'Do you prepare for DELF exams?', answer: 'Yes, we offer DELF A1, A2, B1, and B2 exam preparation.' }, { question: 'Can I learn French online?', answer: 'Yes, both online and offline with the same curriculum quality.' }], seoTitle: 'French Language Classes in Trichy | Success Learning', seoDescription: 'French classes in Trichy. A1 to B2, DELF preparation. Thillai Nagar. Call 98409 79292.' },
    { id: 'japanese', slug: 'japanese-classes', name: 'Japanese', fullName: 'Japanese Language Classes', tagline: 'N5 to N3 Levels', icon: 'bi-flag', color: '#B71C1C', shortDescription: 'Learn Japanese from N5 to N3.', heroTitle: 'Japanese Language Classes in Trichy', heroSubtitle: 'Master Japanese scripts, grammar, and conversation — JLPT preparation.', overview: 'Japan offers excellent career and study opportunities. Our programme covers JLPT N5 to N3 levels, starting with Hiragana and Katakana, progressing to Kanji, grammar, and conversational Japanese.', whoShouldJoin: ['Students planning to study or work in Japan', 'IT professionals targeting Japanese companies', 'Anyone preparing for JLPT exams'], whatYouWillLearn: ['Hiragana, Katakana, and essential Kanji', 'Japanese grammar and sentence patterns', 'Listening and conversational skills', 'Reading comprehension for JLPT', 'Business Japanese basics'], methodology: ['Script-first approach', 'Progressive grammar introduction', 'Audio-visual native Japanese content', 'JLPT-pattern practice tests', 'Conversation sessions'], duration: '3–5 Months per level', mode: 'Online & Offline', batchSize: '5–8 Students', highlights: ['JLPT Preparation', 'Script Training', 'Native Content', 'Career Japanese'], faqs: [{ question: 'Which JLPT levels do you cover?', answer: 'JLPT N5, N4, and N3 levels.' }, { question: 'Is Japanese difficult to learn?', answer: 'Japanese requires learning new scripts, but our structured approach makes it manageable.' }], seoTitle: 'Japanese Language Classes in Trichy | Success Learning', seoDescription: 'Japanese classes in Trichy. JLPT preparation, N5 to N3. Thillai Nagar. Call 98409 79292.' },
    { id: 'pte-oet-duolingo', slug: 'pte-oet-duolingo', name: 'PTE / OET / Duolingo', fullName: 'PTE, OET & Duolingo English Test', tagline: 'Alternative English Proficiency Tests', icon: 'bi-patch-check', color: '#00695C', shortDescription: 'Multiple test preparation options.', heroTitle: 'PTE, OET & Duolingo Coaching in Trichy', heroSubtitle: 'Flexible English proficiency test preparation — choose the right test with expert coaching.', overview: 'PTE Academic is fully computer-based with fast results. OET is for healthcare professionals. Duolingo English Test is an affordable, convenient option. We help you choose the right test and prepare effectively.', whoShouldJoin: ['Students preferring computer-based testing (PTE)', 'Healthcare professionals needing OET', 'Those seeking a quick, affordable test (Duolingo)'], whatYouWillLearn: ['PTE Academic — all question types', 'OET — healthcare communication', 'Duolingo — adaptive test strategies', 'Computer-based test-taking skills', 'Time management'], methodology: ['Test-specific focused preparation', 'Computer-based practice', 'Regular mock tests with scoring', 'Individual feedback on weak areas'], duration: '3–6 Weeks', mode: 'Online & Offline', batchSize: '4–6 Students', highlights: ['Multiple Tests', 'Computer-Based', 'Fast Results', 'Healthcare Focus'], faqs: [{ question: 'Which test should I take?', answer: 'It depends on your goals. We help you choose after understanding your requirements.' }, { question: 'Is Duolingo accepted everywhere?', answer: 'Duolingo ET is accepted by many universities, especially in the US.' }], seoTitle: 'PTE, OET & Duolingo Coaching in Trichy | Success Learning', seoDescription: 'PTE, OET & Duolingo coaching in Trichy. Expert preparation, mock tests. Thillai Nagar. Call 98409 79292.' },
  ];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private seo: SeoService,
    private scrollReveal: ScrollRevealService,
    private el: ElementRef,
  ) {}

  ngOnInit(): void {
    this.route.paramMap.subscribe(params => {
      this.slug = params.get('slug') || '';
      const found = this.coursesData.find(c => c.slug === this.slug);
      if (!found) {
        this.router.navigate(['/courses']);
        return;
      }
      this.course = found;
      this.seo.updateMeta({ title: this.course.seoTitle, description: this.course.seoDescription });

      const countryKeys = this.courseCountryMap[this.slug] || [];
      this.relatedDestinations = countryKeys.map(k => DESTINATIONS.find(d => d.slug === k)!).filter(Boolean).slice(0, 4);
    });
  }

  ngAfterViewInit(): void { this.scrollReveal.observeAll(this.el.nativeElement); }
}
