import { Component, OnInit, AfterViewInit, ElementRef } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { SeoService } from '../../core/services/seo.service';
import { ScrollRevealService } from '../../core/services/scroll-reveal.service';

interface SeoPageData {
  slug: string; title: string; heroTitle: string; heroSubtitle: string;
  courseSlug: string; courseName: string;
  intro: string; benefits: string[]; whyUs: string[];
  seoTitle: string; seoDescription: string;
}

@Component({
  selector: 'app-seo-landing',
  templateUrl: './seo-landing.component.html',
  styleUrls: ['./seo-landing.component.scss'],
})
export class SeoLandingComponent implements OnInit, AfterViewInit {
  page!: SeoPageData;
  faqs: { question: string; answer: string }[] = [];

  private pages: SeoPageData[] = [
    { slug: 'ielts-coaching-in-trichy', title: 'IELTS Coaching in Trichy', heroTitle: 'Best IELTS Coaching Centre in Trichy', heroSubtitle: 'Join Success Learning in Thillai Nagar for expert IELTS preparation with small batches and personalised attention.', courseSlug: 'ielts-coaching', courseName: 'IELTS', intro: 'Looking for the best IELTS coaching in Trichy? Success Learning, located in Thillai Nagar, offers comprehensive IELTS Academic and General Training preparation. Our experienced trainers, small batch sizes, and structured approach have helped hundreds of students achieve their target band scores.', benefits: ['Expert IELTS trainers with years of coaching experience', 'Small batch sizes (5–8 students) for personal attention', 'Weekly mock tests under real exam conditions', 'One-on-one speaking practice sessions', 'Detailed writing feedback with band-score analysis', 'Flexible morning, evening, and weekend batches', 'Both online and offline classes available', 'Affordable fees with no hidden charges'], whyUs: ['Located conveniently in Thillai Nagar, Trichy', 'Proven track record of Band 7+ results', 'Personalised study plans based on diagnostic assessment', 'Cambridge IELTS materials and proprietary worksheets', 'Supportive and encouraging learning environment'], seoTitle: 'IELTS Coaching in Trichy | Best IELTS Training Centre — Success Learning', seoDescription: 'Looking for IELTS coaching in Trichy? Success Learning offers expert IELTS training with small batches, mock tests, and personalised feedback. Thillai Nagar. Call 98409 79292.' },
    { slug: 'best-spoken-english-centre-trichy', title: 'Best Spoken English Centre in Trichy', heroTitle: 'Best Spoken English Centre in Trichy', heroSubtitle: 'Build English speaking confidence with interactive, practice-focused training at Success Learning.', courseSlug: 'spoken-english', courseName: 'Spoken English', intro: 'Success Learning is one of Trichy\'s most trusted spoken English training centres. Our interactive, practice-based approach helps students and professionals overcome hesitation and communicate confidently in English — in conversations, interviews, presentations, and everyday situations.', benefits: ['Interactive sessions — no boring lectures', 'Daily speaking practice and assignments', 'Pronunciation and accent improvement', 'Interview and presentation preparation', 'Group discussions and role-playing', 'Beginner to advanced levels available', 'Flexible batch timings', 'Both online and offline options'], whyUs: ['Focus on practical speaking, not just grammar theory', 'Small batches for maximum speaking time per student', 'Encouraging, non-judgmental environment', 'Trainers who understand Indian English challenges', 'Visible improvement within 3–4 weeks'], seoTitle: 'Best Spoken English Centre in Trichy | Success Learning', seoDescription: 'Looking for spoken English classes in Trichy? Success Learning offers interactive, practice-focused English speaking training. Thillai Nagar. Call 98409 79292.' },
    { slug: 'german-language-classes-trichy', title: 'German Language Classes in Trichy', heroTitle: 'German Language Classes in Trichy', heroSubtitle: 'Learn German from A1 to B2 with Goethe-Zertifikat preparation at Success Learning.', courseSlug: 'german-classes', courseName: 'German', intro: 'Planning to study or work in Germany? Success Learning offers structured German language classes from A1 to B2 level in Trichy. Our CEFR-aligned curriculum prepares you for Goethe-Zertifikat examinations with conversational practice and cultural context.', benefits: ['A1 to B2 levels following CEFR framework', 'Goethe-Zertifikat exam preparation', 'Conversational practice in every session', 'Audio-visual learning materials', 'Cultural context for real-world application', 'Small batches for individual attention', 'Flexible timings', 'Online and offline classes'], whyUs: ['Structured curriculum aligned with Goethe standards', 'Experienced German language instructors', 'Focus on speaking, not just grammar', 'Regular assessments tracking your progress', 'Guidance on study opportunities in Germany'], seoTitle: 'German Language Classes in Trichy | Success Learning', seoDescription: 'Learn German in Trichy at Success Learning. A1 to B2 levels, Goethe preparation, small batches. Thillai Nagar. Call 98409 79292.' },
    { slug: 'french-coaching-trichy', title: 'French Coaching in Trichy', heroTitle: 'French Language Coaching in Trichy', heroSubtitle: 'Learn French from A1 to B2 with DELF preparation at Success Learning Trichy.', courseSlug: 'french-classes', courseName: 'French', intro: 'Success Learning offers comprehensive French language training in Trichy, covering A1 to B2 levels with DELF exam preparation. Whether you are planning to study in France, Canada, or simply want to learn a beautiful language, our programme provides the right foundation.', benefits: ['CEFR-aligned curriculum from A1 to B2', 'DELF exam preparation with mock tests', 'Interactive speaking-focused sessions', 'Cultural immersion activities', 'Audio-visual learning resources', 'Small batch sizes', 'Flexible timing options', 'Online and offline classes'], whyUs: ['Experienced French language instructors', 'Balance of grammar, vocabulary, and conversation', 'Regular DELF-pattern assessments', 'Supportive and engaging classroom environment', 'Guidance on opportunities in French-speaking countries'], seoTitle: 'French Coaching in Trichy | Success Learning', seoDescription: 'Learn French in Trichy at Success Learning. A1 to B2, DELF preparation, interactive sessions. Thillai Nagar. Call 98409 79292.' },
    { slug: 'gre-coaching-centre-trichy', title: 'GRE Coaching Centre in Trichy', heroTitle: 'GRE Coaching Centre in Trichy', heroSubtitle: 'Score 310+ on GRE with expert coaching in Verbal, Quant & AWA at Success Learning.', courseSlug: 'gre-coaching', courseName: 'GRE', intro: 'Preparing for the GRE? Success Learning in Trichy offers focused GRE coaching with concept-based teaching, vocabulary building, and extensive mock tests. Our small batches ensure every student gets the attention they need to achieve a competitive score.', benefits: ['Comprehensive Verbal and Quantitative preparation', 'Analytical Writing Assessment coaching', 'Adaptive test practice matching GRE format', 'High-frequency vocabulary building programme', 'Weekly full-length mock tests', 'Detailed score analysis and improvement tracking', 'Small batches (4–6 students)', 'Flexible scheduling options'], whyUs: ['Concept-first teaching approach', 'Experienced trainers who understand GRE patterns', 'Personalised study plans based on diagnostic tests', 'Focus on strategy, not just content', 'Track record of 310+ scores'], seoTitle: 'GRE Coaching Centre in Trichy | Success Learning', seoDescription: 'GRE coaching in Trichy at Success Learning. Expert Verbal, Quant & AWA training, mock tests, small batches. Thillai Nagar. Call 98409 79292.' },
    { slug: 'gmat-training-trichy', title: 'GMAT Training in Trichy', heroTitle: 'GMAT Training Centre in Trichy', heroSubtitle: 'Ace the GMAT with strategic preparation at Success Learning Trichy.', courseSlug: 'gmat-coaching', courseName: 'GMAT', intro: 'Success Learning offers expert GMAT coaching in Trichy for MBA aspirants. Our structured programme covers all GMAT sections with adaptive practice, score analytics, and personalised improvement plans to help you achieve your target score.', benefits: ['All GMAT sections covered — Quant, Verbal, DI, AWA', 'GMAT Focus Edition curriculum', 'Adaptive difficulty mock tests', 'Score analytics and improvement tracking', 'Small batches (4–6 students)', 'Flexible weekday and weekend options', 'Online and offline classes', 'MBA application guidance'], whyUs: ['Updated curriculum for GMAT Focus Edition', 'Experienced GMAT trainers', 'Data-driven approach to improvement', 'Focus on high-impact question types', 'Supportive learning environment'], seoTitle: 'GMAT Training in Trichy | Success Learning', seoDescription: 'GMAT coaching in Trichy at Success Learning. Adaptive mock tests, score analytics, small batches. Thillai Nagar. Call 98409 79292.' },
  ];

  constructor(private route: ActivatedRoute, private router: Router, private seo: SeoService, private scrollReveal: ScrollRevealService, private el: ElementRef) {}

  ngOnInit(): void {
    const slug = this.route.snapshot.data['slug'] || '';
    const found = this.pages.find(p => p.slug === slug);
    if (!found) { this.router.navigate(['/']); return; }
    this.page = found;
    this.seo.updateMeta({ title: this.page.seoTitle, description: this.page.seoDescription });
    this.faqs = [
      { question: `Where is Success Learning located?`, answer: 'We are located at D73, 7th Cross St W, Thillai Nagar East, Tiruchirappalli, Tamil Nadu 620018.' },
      { question: `What are the batch sizes for ${this.page.courseName}?`, answer: 'We maintain small batch sizes of 4–8 students to ensure personal attention for every learner.' },
      { question: `Do you offer online classes for ${this.page.courseName}?`, answer: 'Yes, we offer both online and offline classes with the same curriculum quality.' },
      { question: `How can I enrol for ${this.page.courseName} coaching?`, answer: 'You can call us at 98409 79292, WhatsApp us, or visit our centre in Thillai Nagar for a free consultation.' },
    ];
  }

  ngAfterViewInit(): void { this.scrollReveal.observeAll(this.el.nativeElement); }
}
